"""
Move all data types into the same namespace
"""

from transforms.main import (
    axis_angle_to_euler,
    axis_angle_to_matrix,
    # axis / angle
    axis_angle_to_quaternion,
    euler_filter,
    euler_random,
    euler_reorder,
    euler_slerp,
    # euler
    euler_to_matrix,
    euler_to_quaternion,
    matrix_decompose,
    matrix_delta,
    matrix_flatten,
    # matrix
    matrix_identity,
    matrix_interpolate,
    matrix_inverse,
    matrix_local,
    matrix_multiply,
    matrix_normalize,
    matrix_point_multiply,
    matrix_random,
    matrix_slerp,
    matrix_to_euler,
    matrix_to_quaternion,
    matrix_transpose,
    matrix_weighted_rotational,
    matrix_weighted_transformation,
    quaternion_add,
    quaternion_conjugate,
    quaternion_dot,
    quaternion_inverse,
    quaternion_multiply,
    quaternion_negate,
    quaternion_normalize,
    quaternion_random,
    # quaternion
    quaternion_slerp,
    quaternion_sub,
    quaternion_to_euler,
    quaternion_to_matrix,
    vector_angle,
    vector_arc_to_euler,
    vector_arc_to_matrix,
    vector_arc_to_quaternion,
    vector_cross,
    vector_dot,
    vector_lerp,
    vector_magnitude,
    vector_normalize,
    vector_random,
    vector_slerp,
    vector_to_euler,
    # vector
    vector_to_matrix,
    vector_to_quaternion,
    X,
    # constants
    XYZ,
    XZY,
    Y,
    YXZ,
    YZX,
    Z,
    ZXY,
    ZYX,
)